= i18n-formerly-assigned
:toc:

image:https://github.com/mihxil/i18n-formerly-assigned/actions/workflows/maven.yml/badge.svg?[Build Status,link=https://github.com/mihxil/i18n-formerly-assigned/actions/workflows/maven.yml]
image:https://img.shields.io/maven-central/v/org.meeuw.i18n/i18n-formerly-assigned.svg?label=Maven%20Central[Maven Central,link=https://search.maven.org/search?q=g:%22org.meeuw.i18n%22]
//image:https://img.shields.io/nexus/s/https/oss.sonatype.org/org.meeuw.i18n/i18n-formerly-assigned.svg[snapshots,link=https://oss.sonatype.org/content/repositories/snapshots/org/meeuw/i18n/i18n-formerly-assigned/]
image:http://www.javadoc.io/badge/org.meeuw.i18n/i18n-formerly-assigned.svg?color=blue[javadoc,link=https://www.javadoc.io/doc/org.meeuw.i18n/i18n-formerly-assigned/latest/org.meeuw.i18n.formerlyassigned/org/meeuw/i18n/formerlyassigned/FormerlyAssignedCountryCode.html]


== Introduction

This project creates support for 'formerly assigned country codes' (in the form of the enum `org.meeuw.i18n.formerlyassigned.FormerlyAssignedCountryCode` . See https://en.wikipedia.org/wiki/ISO_3166-3[ISO 3166-3]

The idea was to use this in conjuction with https://github.com/TakahikoKawasaki/nv-i18n[neovisionaries nv-i18n] which supports current country codes according to https://en.wikipedia.org/wiki/ISO_3166-1[ISO 3166-1], and https://github.com/tobias-/i18n-subdivisions[i18n subdivisions] with support for subdivisions of countries according to https://en.wikipedia.org/wiki/ISO_3166-2[ISO 3166-2].

This is now done via https://github.com/mihxil/i18n-regions[i18n regions].

== Implementation

The list of enums values is created by scraping the concerning wikipedia page, using the groovy script in `src/main/script`, which is called from the maven build.

Therefore the source code on github doesn't really help to browse the full list. The javadoc _would_, so please check the link above.


== Java version

The artifact is compatible with java 8 and higher. Only  `module-info.class` is compiled with java target version 11.
